brain_two/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListView,
    TodoDetailView,
    TodoCreateView,
)


urlpatterns = [
    path("", TodoListView.as_view(), name="list_todos"),
    path("<int:pk>/", TodoDetailView.as_view(), name="show_todolist"),
    path("create/", TodoCreateView.as_view(), name="create_todolist"),
]

todos/models.py
from tkinter import CASCADE
from django.db import models
from django.forms import DateTimeField

# from django.conf import settings

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = DateTimeField()
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from todos.models import TodoList
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your views here.


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    field = ["name"]

todos/templates/base.html
<!DOCTYPE html>

<html>

<head>
    <title></title>
</head>

<body>
    <header>
        <nav>

        </nav>
    </header>
    {% block content %}
    {% endblock content %}
</body>


</html>

todos/templates/todos/create.html
{% extends 'base.html' %}



{% block content %}

<main>
    <div>
        <h1>Create a new list</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Submit</button>
        </form>
    
    </div>
</main>

{% endblock content %}

todos/templates/todos/detail.html
{% extends 'base.html' %}



{% block content %}
<main>
    <div>
        <h1>{{todolist.name}}</h1>
        <h2>Tasks</h2>

        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for item in todolist.items.all %}

                <tr>
                    <td>{{ item.task }}</td>
                    <td>{{ item.due_date|date:"M d, Y" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</main>
{% endblock content %}

todos/templates/todos/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>My Lists</h1>
        <p><a href="{% url 'create_todolist' %}">Create a new list</a></p>
    </div>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of items</th>
            </tr>
        </thead>
        <tbody>
            {% for list in todolist_list %}
            <tr>
                <td><a href="{% url 'show_todolist' list.pk %}">{{ list.name }}</a></td>

                <td> {{ list.items.all | length }} </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</main>
{% endblock content %}